// Generated by gencpp from file agn_leg_detection/legmsg.msg
// DO NOT EDIT!


#ifndef AGN_LEG_DETECTION_MESSAGE_LEGMSG_H
#define AGN_LEG_DETECTION_MESSAGE_LEGMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agn_leg_detection
{
template <class ContainerAllocator>
struct legmsg_
{
  typedef legmsg_<ContainerAllocator> Type;

  legmsg_()
    : count()
    , first(0)
    , end(0)  {
    }
  legmsg_(const ContainerAllocator& _alloc)
    : count(_alloc)
    , first(0)
    , end(0)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _count_type;
  _count_type count;

   typedef int64_t _first_type;
  _first_type first;

   typedef int64_t _end_type;
  _end_type end;





  typedef boost::shared_ptr< ::agn_leg_detection::legmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agn_leg_detection::legmsg_<ContainerAllocator> const> ConstPtr;

}; // struct legmsg_

typedef ::agn_leg_detection::legmsg_<std::allocator<void> > legmsg;

typedef boost::shared_ptr< ::agn_leg_detection::legmsg > legmsgPtr;
typedef boost::shared_ptr< ::agn_leg_detection::legmsg const> legmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agn_leg_detection::legmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agn_leg_detection::legmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agn_leg_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'agn_leg_detection': ['/home/plugit/lidar_mapping/src/agn_leg_detection/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agn_leg_detection::legmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agn_leg_detection::legmsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agn_leg_detection::legmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agn_leg_detection::legmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agn_leg_detection::legmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agn_leg_detection::legmsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agn_leg_detection::legmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "575cf73be3bb238f762d331a4b3c6e57";
  }

  static const char* value(const ::agn_leg_detection::legmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x575cf73be3bb238fULL;
  static const uint64_t static_value2 = 0x762d331a4b3c6e57ULL;
};

template<class ContainerAllocator>
struct DataType< ::agn_leg_detection::legmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agn_leg_detection/legmsg";
  }

  static const char* value(const ::agn_leg_detection::legmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agn_leg_detection::legmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] count\n\
int64 first\n\
int64 end\n\
";
  }

  static const char* value(const ::agn_leg_detection::legmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agn_leg_detection::legmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
      stream.next(m.first);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct legmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agn_leg_detection::legmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agn_leg_detection::legmsg_<ContainerAllocator>& v)
  {
    s << indent << "count[]" << std::endl;
    for (size_t i = 0; i < v.count.size(); ++i)
    {
      s << indent << "  count[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.count[i]);
    }
    s << indent << "first: ";
    Printer<int64_t>::stream(s, indent + "  ", v.first);
    s << indent << "end: ";
    Printer<int64_t>::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGN_LEG_DETECTION_MESSAGE_LEGMSG_H
