// Generated by gencpp from file find_moving_objects/LaserScanArray.msg
// DO NOT EDIT!


#ifndef FIND_MOVING_OBJECTS_MESSAGE_LASERSCANARRAY_H
#define FIND_MOVING_OBJECTS_MESSAGE_LASERSCANARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/LaserScan.h>

namespace find_moving_objects
{
template <class ContainerAllocator>
struct LaserScanArray_
{
  typedef LaserScanArray_<ContainerAllocator> Type;

  LaserScanArray_()
    : header()
    , msgs()  {
    }
  LaserScanArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , msgs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::sensor_msgs::LaserScan_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::LaserScan_<ContainerAllocator> >::other >  _msgs_type;
  _msgs_type msgs;





  typedef boost::shared_ptr< ::find_moving_objects::LaserScanArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::find_moving_objects::LaserScanArray_<ContainerAllocator> const> ConstPtr;

}; // struct LaserScanArray_

typedef ::find_moving_objects::LaserScanArray_<std::allocator<void> > LaserScanArray;

typedef boost::shared_ptr< ::find_moving_objects::LaserScanArray > LaserScanArrayPtr;
typedef boost::shared_ptr< ::find_moving_objects::LaserScanArray const> LaserScanArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::find_moving_objects::LaserScanArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace find_moving_objects

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'find_moving_objects': ['/home/plugit/lidar_mapping/src/find_moving_objects/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::find_moving_objects::LaserScanArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_moving_objects::LaserScanArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_moving_objects::LaserScanArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fef4bfad359e95377aae0ce4e718ce9";
  }

  static const char* value(const ::find_moving_objects::LaserScanArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fef4bfad359e953ULL;
  static const uint64_t static_value2 = 0x77aae0ce4e718ce9ULL;
};

template<class ContainerAllocator>
struct DataType< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "find_moving_objects/LaserScanArray";
  }

  static const char* value(const ::find_moving_objects::LaserScanArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# If using this message type, then:\n\
#   the time stamp of this message and the ones in the array must be highly related, or better yet, equal; and\n\
#   the frame_id of each message in the array must be transformable into the frame_id of this message.\n\
# Basically, all LaserScan messages in the array should come from different sensor entities on the same sensor unit.\n\
# This message type could, for example, be used for a multi-diode Lidar or similar.\n\
\n\
Header header\n\
sensor_msgs/LaserScan[] msgs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/LaserScan\n\
# Single scan from a planar laser range-finder\n\
#\n\
# If you have another ranging device with different behavior (e.g. a sonar\n\
# array), please find or create a different message, since applications\n\
# will make fairly laser-specific assumptions about this data\n\
\n\
Header header            # timestamp in the header is the acquisition time of \n\
                         # the first ray in the scan.\n\
                         #\n\
                         # in frame frame_id, angles are measured around \n\
                         # the positive Z axis (counterclockwise, if Z is up)\n\
                         # with zero angle being forward along the x axis\n\
                         \n\
float32 angle_min        # start angle of the scan [rad]\n\
float32 angle_max        # end angle of the scan [rad]\n\
float32 angle_increment  # angular distance between measurements [rad]\n\
\n\
float32 time_increment   # time between measurements [seconds] - if your scanner\n\
                         # is moving, this will be used in interpolating position\n\
                         # of 3d points\n\
float32 scan_time        # time between scans [seconds]\n\
\n\
float32 range_min        # minimum range value [m]\n\
float32 range_max        # maximum range value [m]\n\
\n\
float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n\
float32[] intensities    # intensity data [device-specific units].  If your\n\
                         # device does not provide intensities, please leave\n\
                         # the array empty.\n\
";
  }

  static const char* value(const ::find_moving_objects::LaserScanArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.msgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaserScanArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::find_moving_objects::LaserScanArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::find_moving_objects::LaserScanArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "msgs[]" << std::endl;
    for (size_t i = 0; i < v.msgs.size(); ++i)
    {
      s << indent << "  msgs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "    ", v.msgs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIND_MOVING_OBJECTS_MESSAGE_LASERSCANARRAY_H
