// Generated by gencpp from file find_moving_objects/MovingObject.msg
// DO NOT EDIT!


#ifndef FIND_MOVING_OBJECTS_MESSAGE_MOVINGOBJECT_H
#define FIND_MOVING_OBJECTS_MESSAGE_MOVINGOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace find_moving_objects
{
template <class ContainerAllocator>
struct MovingObject_
{
  typedef MovingObject_<ContainerAllocator> Type;

  MovingObject_()
    : header()
    , map_frame()
    , fixed_frame()
    , base_frame()
    , seen_width(0.0)
    , angle_begin(0.0)
    , angle_end(0.0)
    , distance_at_angle_begin(0.0)
    , distance_at_angle_end(0.0)
    , distance(0.0)
    , position_in_map_frame()
    , position_in_fixed_frame()
    , position_in_base_frame()
    , position()
    , velocity_in_map_frame()
    , velocity_in_fixed_frame()
    , velocity_in_base_frame()
    , velocity()
    , velocity_normalized_in_map_frame()
    , velocity_normalized_in_fixed_frame()
    , velocity_normalized_in_base_frame()
    , velocity_normalized()
    , speed_in_map_frame(0.0)
    , speed_in_fixed_frame(0.0)
    , speed_in_base_frame(0.0)
    , speed(0.0)
    , closest_point_in_map_frame()
    , closest_point_in_fixed_frame()
    , closest_point_in_base_frame()
    , closest_point()
    , closest_distance(0.0)
    , angle_for_closest_distance(0.0)
    , confidence(0.0)  {
    }
  MovingObject_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , map_frame(_alloc)
    , fixed_frame(_alloc)
    , base_frame(_alloc)
    , seen_width(0.0)
    , angle_begin(0.0)
    , angle_end(0.0)
    , distance_at_angle_begin(0.0)
    , distance_at_angle_end(0.0)
    , distance(0.0)
    , position_in_map_frame(_alloc)
    , position_in_fixed_frame(_alloc)
    , position_in_base_frame(_alloc)
    , position(_alloc)
    , velocity_in_map_frame(_alloc)
    , velocity_in_fixed_frame(_alloc)
    , velocity_in_base_frame(_alloc)
    , velocity(_alloc)
    , velocity_normalized_in_map_frame(_alloc)
    , velocity_normalized_in_fixed_frame(_alloc)
    , velocity_normalized_in_base_frame(_alloc)
    , velocity_normalized(_alloc)
    , speed_in_map_frame(0.0)
    , speed_in_fixed_frame(0.0)
    , speed_in_base_frame(0.0)
    , speed(0.0)
    , closest_point_in_map_frame(_alloc)
    , closest_point_in_fixed_frame(_alloc)
    , closest_point_in_base_frame(_alloc)
    , closest_point(_alloc)
    , closest_distance(0.0)
    , angle_for_closest_distance(0.0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _map_frame_type;
  _map_frame_type map_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fixed_frame_type;
  _fixed_frame_type fixed_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _base_frame_type;
  _base_frame_type base_frame;

   typedef double _seen_width_type;
  _seen_width_type seen_width;

   typedef double _angle_begin_type;
  _angle_begin_type angle_begin;

   typedef double _angle_end_type;
  _angle_end_type angle_end;

   typedef double _distance_at_angle_begin_type;
  _distance_at_angle_begin_type distance_at_angle_begin;

   typedef double _distance_at_angle_end_type;
  _distance_at_angle_end_type distance_at_angle_end;

   typedef double _distance_type;
  _distance_type distance;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_in_map_frame_type;
  _position_in_map_frame_type position_in_map_frame;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_in_fixed_frame_type;
  _position_in_fixed_frame_type position_in_fixed_frame;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_in_base_frame_type;
  _position_in_base_frame_type position_in_base_frame;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_in_map_frame_type;
  _velocity_in_map_frame_type velocity_in_map_frame;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_in_fixed_frame_type;
  _velocity_in_fixed_frame_type velocity_in_fixed_frame;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_in_base_frame_type;
  _velocity_in_base_frame_type velocity_in_base_frame;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_normalized_in_map_frame_type;
  _velocity_normalized_in_map_frame_type velocity_normalized_in_map_frame;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_normalized_in_fixed_frame_type;
  _velocity_normalized_in_fixed_frame_type velocity_normalized_in_fixed_frame;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_normalized_in_base_frame_type;
  _velocity_normalized_in_base_frame_type velocity_normalized_in_base_frame;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_normalized_type;
  _velocity_normalized_type velocity_normalized;

   typedef double _speed_in_map_frame_type;
  _speed_in_map_frame_type speed_in_map_frame;

   typedef double _speed_in_fixed_frame_type;
  _speed_in_fixed_frame_type speed_in_fixed_frame;

   typedef double _speed_in_base_frame_type;
  _speed_in_base_frame_type speed_in_base_frame;

   typedef double _speed_type;
  _speed_type speed;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _closest_point_in_map_frame_type;
  _closest_point_in_map_frame_type closest_point_in_map_frame;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _closest_point_in_fixed_frame_type;
  _closest_point_in_fixed_frame_type closest_point_in_fixed_frame;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _closest_point_in_base_frame_type;
  _closest_point_in_base_frame_type closest_point_in_base_frame;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _closest_point_type;
  _closest_point_type closest_point;

   typedef double _closest_distance_type;
  _closest_distance_type closest_distance;

   typedef double _angle_for_closest_distance_type;
  _angle_for_closest_distance_type angle_for_closest_distance;

   typedef double _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::find_moving_objects::MovingObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::find_moving_objects::MovingObject_<ContainerAllocator> const> ConstPtr;

}; // struct MovingObject_

typedef ::find_moving_objects::MovingObject_<std::allocator<void> > MovingObject;

typedef boost::shared_ptr< ::find_moving_objects::MovingObject > MovingObjectPtr;
typedef boost::shared_ptr< ::find_moving_objects::MovingObject const> MovingObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::find_moving_objects::MovingObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::find_moving_objects::MovingObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace find_moving_objects

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'find_moving_objects': ['/home/plugit/lidar_mapping/src/find_moving_objects/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::find_moving_objects::MovingObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::find_moving_objects::MovingObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_moving_objects::MovingObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_moving_objects::MovingObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_moving_objects::MovingObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_moving_objects::MovingObject_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::find_moving_objects::MovingObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "471d2ca009fdd96d2081f5d9404ce5d6";
  }

  static const char* value(const ::find_moving_objects::MovingObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x471d2ca009fdd96dULL;
  static const uint64_t static_value2 = 0x2081f5d9404ce5d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::find_moving_objects::MovingObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "find_moving_objects/MovingObject";
  }

  static const char* value(const ::find_moving_objects::MovingObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::find_moving_objects::MovingObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# stamp is the time at which the sensor scanned this \n\
# object. \n\
# frame_id is the frame (i.e. coordinate system) of the \n\
# sensor - this is the frame in which the given relative \n\
# information below (the variables position, velocity, \n\
# speed, angle_* etc.) is valid.\n\
# seq is not really used.\n\
Header header\n\
\n\
# The frame which is considered world-fixed and never \n\
# moves. Note that the robot's position in this frame \n\
# can be discontinuous.\n\
# The variables *_in_map_frame below are specified in \n\
# this frame.\n\
string map_frame\n\
\n\
# The frame in which the movement of the robot is always\n\
# continuous and in which all transforms are made.\n\
# The variables *_in_fixed_frame below are \n\
# specified in this frame.\n\
string fixed_frame\n\
\n\
# The frame which is considered fixed on the robot and \n\
# in which the variables *_in_base_frame below are\n\
# specified.\n\
string base_frame\n\
\n\
# The width of the object as seen by the given \n\
# sensor (calculated based on angle_begin, angle_end,\n\
# distance_angle_begin and distance_angle_end as \n\
# given below using the law of cosine).\n\
float64 seen_width\n\
\n\
# In frame header.frame_id, angles are measured around \n\
# the positive Z axis (counterclockwise; Z is pointing up)\n\
# with zero angle being forward along the x axis, provided\n\
# that the frame is not an optical/camera frame.\n\
# In case of an optical frame (Z is pointing forward and Y\n\
# is pointing down), then angles are measured around the \n\
# negative Y axis.\n\
# The angles given specify where the object is to be\n\
# found in the frame header.frame_id (this is thus \n\
# relative to the X-axis of the sensor in a regular frame\n\
# and relative the Z-axis, but negated, in an optical frame).\n\
float64 angle_begin\n\
float64 angle_end\n\
\n\
# The scanned distances to the object's end points as \n\
# specified by angle_begin and angle_end.\n\
float64 distance_at_angle_begin\n\
float64 distance_at_angle_end\n\
\n\
# The averaged distance (approximated to be at \n\
# (angle_begin+angle_end)/2) from the sensor to the seen\n\
# object.\n\
float64 distance\n\
\n\
# Position and velocity of the object.\n\
geometry_msgs/Point position_in_map_frame\n\
geometry_msgs/Point position_in_fixed_frame\n\
geometry_msgs/Point position_in_base_frame\n\
geometry_msgs/Point position\n\
geometry_msgs/Vector3 velocity_in_map_frame\n\
geometry_msgs/Vector3 velocity_in_fixed_frame\n\
geometry_msgs/Vector3 velocity_in_base_frame\n\
geometry_msgs/Vector3 velocity\n\
\n\
# For convenience, the normalized velocity vector is\n\
# also given, along with the scale factor (speed).\n\
geometry_msgs/Vector3 velocity_normalized_in_map_frame\n\
geometry_msgs/Vector3 velocity_normalized_in_fixed_frame\n\
geometry_msgs/Vector3 velocity_normalized_in_base_frame\n\
geometry_msgs/Vector3 velocity_normalized\n\
float64 speed_in_map_frame\n\
float64 speed_in_fixed_frame\n\
float64 speed_in_base_frame\n\
float64 speed\n\
\n\
# The point on the object closest to the sensor.\n\
geometry_msgs/Point closest_point_in_map_frame\n\
geometry_msgs/Point closest_point_in_fixed_frame\n\
geometry_msgs/Point closest_point_in_base_frame\n\
geometry_msgs/Point closest_point\n\
\n\
# For convenience, the distance from the sensor to the \n\
# closest point on the object and at what angle it is to \n\
# be found in relation to the sensor (i.e. \n\
# header.frame_id).\n\
float64 closest_distance\n\
float64 angle_for_closest_distance\n\
\n\
# A measure on how confident the sending node is about \n\
# the specified information.\n\
float64 confidence\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::find_moving_objects::MovingObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::find_moving_objects::MovingObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.map_frame);
      stream.next(m.fixed_frame);
      stream.next(m.base_frame);
      stream.next(m.seen_width);
      stream.next(m.angle_begin);
      stream.next(m.angle_end);
      stream.next(m.distance_at_angle_begin);
      stream.next(m.distance_at_angle_end);
      stream.next(m.distance);
      stream.next(m.position_in_map_frame);
      stream.next(m.position_in_fixed_frame);
      stream.next(m.position_in_base_frame);
      stream.next(m.position);
      stream.next(m.velocity_in_map_frame);
      stream.next(m.velocity_in_fixed_frame);
      stream.next(m.velocity_in_base_frame);
      stream.next(m.velocity);
      stream.next(m.velocity_normalized_in_map_frame);
      stream.next(m.velocity_normalized_in_fixed_frame);
      stream.next(m.velocity_normalized_in_base_frame);
      stream.next(m.velocity_normalized);
      stream.next(m.speed_in_map_frame);
      stream.next(m.speed_in_fixed_frame);
      stream.next(m.speed_in_base_frame);
      stream.next(m.speed);
      stream.next(m.closest_point_in_map_frame);
      stream.next(m.closest_point_in_fixed_frame);
      stream.next(m.closest_point_in_base_frame);
      stream.next(m.closest_point);
      stream.next(m.closest_distance);
      stream.next(m.angle_for_closest_distance);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovingObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::find_moving_objects::MovingObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::find_moving_objects::MovingObject_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "map_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.map_frame);
    s << indent << "fixed_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fixed_frame);
    s << indent << "base_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.base_frame);
    s << indent << "seen_width: ";
    Printer<double>::stream(s, indent + "  ", v.seen_width);
    s << indent << "angle_begin: ";
    Printer<double>::stream(s, indent + "  ", v.angle_begin);
    s << indent << "angle_end: ";
    Printer<double>::stream(s, indent + "  ", v.angle_end);
    s << indent << "distance_at_angle_begin: ";
    Printer<double>::stream(s, indent + "  ", v.distance_at_angle_begin);
    s << indent << "distance_at_angle_end: ";
    Printer<double>::stream(s, indent + "  ", v.distance_at_angle_end);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "position_in_map_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position_in_map_frame);
    s << indent << "position_in_fixed_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position_in_fixed_frame);
    s << indent << "position_in_base_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position_in_base_frame);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity_in_map_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_in_map_frame);
    s << indent << "velocity_in_fixed_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_in_fixed_frame);
    s << indent << "velocity_in_base_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_in_base_frame);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "velocity_normalized_in_map_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_normalized_in_map_frame);
    s << indent << "velocity_normalized_in_fixed_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_normalized_in_fixed_frame);
    s << indent << "velocity_normalized_in_base_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_normalized_in_base_frame);
    s << indent << "velocity_normalized: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_normalized);
    s << indent << "speed_in_map_frame: ";
    Printer<double>::stream(s, indent + "  ", v.speed_in_map_frame);
    s << indent << "speed_in_fixed_frame: ";
    Printer<double>::stream(s, indent + "  ", v.speed_in_fixed_frame);
    s << indent << "speed_in_base_frame: ";
    Printer<double>::stream(s, indent + "  ", v.speed_in_base_frame);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "closest_point_in_map_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.closest_point_in_map_frame);
    s << indent << "closest_point_in_fixed_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.closest_point_in_fixed_frame);
    s << indent << "closest_point_in_base_frame: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.closest_point_in_base_frame);
    s << indent << "closest_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.closest_point);
    s << indent << "closest_distance: ";
    Printer<double>::stream(s, indent + "  ", v.closest_distance);
    s << indent << "angle_for_closest_distance: ";
    Printer<double>::stream(s, indent + "  ", v.angle_for_closest_distance);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIND_MOVING_OBJECTS_MESSAGE_MOVINGOBJECT_H
