// Generated by gencpp from file find_moving_objects/PointCloud2Array.msg
// DO NOT EDIT!


#ifndef FIND_MOVING_OBJECTS_MESSAGE_POINTCLOUD2ARRAY_H
#define FIND_MOVING_OBJECTS_MESSAGE_POINTCLOUD2ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/PointCloud2.h>

namespace find_moving_objects
{
template <class ContainerAllocator>
struct PointCloud2Array_
{
  typedef PointCloud2Array_<ContainerAllocator> Type;

  PointCloud2Array_()
    : header()
    , msgs()  {
    }
  PointCloud2Array_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , msgs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::sensor_msgs::PointCloud2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::other >  _msgs_type;
  _msgs_type msgs;





  typedef boost::shared_ptr< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> const> ConstPtr;

}; // struct PointCloud2Array_

typedef ::find_moving_objects::PointCloud2Array_<std::allocator<void> > PointCloud2Array;

typedef boost::shared_ptr< ::find_moving_objects::PointCloud2Array > PointCloud2ArrayPtr;
typedef boost::shared_ptr< ::find_moving_objects::PointCloud2Array const> PointCloud2ArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::find_moving_objects::PointCloud2Array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace find_moving_objects

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'find_moving_objects': ['/home/plugit/lidar_mapping/src/find_moving_objects/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f85282bae913047b119eb2b9f5bb1db";
  }

  static const char* value(const ::find_moving_objects::PointCloud2Array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f85282bae913047ULL;
  static const uint64_t static_value2 = 0xb119eb2b9f5bb1dbULL;
};

template<class ContainerAllocator>
struct DataType< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "find_moving_objects/PointCloud2Array";
  }

  static const char* value(const ::find_moving_objects::PointCloud2Array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# If using this message type, then:\n\
#   the time stamp of this message and the ones in the array must be highly related, or better yet, equal; and\n\
#   the frame_id of each message in the array must be transformable into the frame_id of this message.\n\
# Basically, all PointCloud2 messages in the array should come from different sensor entities on the same sensor unit.\n\
# This message type could, for example, be used for a multi-lense camera unit, or a multi-diode Lidar.\n\
\n\
Header header\n\
sensor_msgs/PointCloud2[] msgs\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
";
  }

  static const char* value(const ::find_moving_objects::PointCloud2Array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.msgs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PointCloud2Array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::find_moving_objects::PointCloud2Array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::find_moving_objects::PointCloud2Array_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "msgs[]" << std::endl;
    for (size_t i = 0; i < v.msgs.size(); ++i)
    {
      s << indent << "  msgs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "    ", v.msgs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIND_MOVING_OBJECTS_MESSAGE_POINTCLOUD2ARRAY_H
