// Generated by gencpp from file socket_manager/GetDistanceFromWallResponse.msg
// DO NOT EDIT!


#ifndef SOCKET_MANAGER_MESSAGE_GETDISTANCEFROMWALLRESPONSE_H
#define SOCKET_MANAGER_MESSAGE_GETDISTANCEFROMWALLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace socket_manager
{
template <class ContainerAllocator>
struct GetDistanceFromWallResponse_
{
  typedef GetDistanceFromWallResponse_<ContainerAllocator> Type;

  GetDistanceFromWallResponse_()
    : distance(0.0)
    , angle(0.0)  {
    }
  GetDistanceFromWallResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_type;
  _distance_type distance;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetDistanceFromWallResponse_

typedef ::socket_manager::GetDistanceFromWallResponse_<std::allocator<void> > GetDistanceFromWallResponse;

typedef boost::shared_ptr< ::socket_manager::GetDistanceFromWallResponse > GetDistanceFromWallResponsePtr;
typedef boost::shared_ptr< ::socket_manager::GetDistanceFromWallResponse const> GetDistanceFromWallResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace socket_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1f1d53743f4592ee455aa3eaf9019457";
  }

  static const char* value(const ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1f1d53743f4592eeULL;
  static const uint64_t static_value2 = 0x455aa3eaf9019457ULL;
};

template<class ContainerAllocator>
struct DataType< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "socket_manager/GetDistanceFromWallResponse";
  }

  static const char* value(const ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 distance\n\
float64 angle\n\
";
  }

  static const char* value(const ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetDistanceFromWallResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::socket_manager::GetDistanceFromWallResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOCKET_MANAGER_MESSAGE_GETDISTANCEFROMWALLRESPONSE_H
