// Generated by gencpp from file socket_manager/GetDistanceFromWall.msg
// DO NOT EDIT!


#ifndef SOCKET_MANAGER_MESSAGE_GETDISTANCEFROMWALL_H
#define SOCKET_MANAGER_MESSAGE_GETDISTANCEFROMWALL_H

#include <ros/service_traits.h>


#include <socket_manager/GetDistanceFromWallRequest.h>
#include <socket_manager/GetDistanceFromWallResponse.h>


namespace socket_manager
{

struct GetDistanceFromWall
{

typedef GetDistanceFromWallRequest Request;
typedef GetDistanceFromWallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDistanceFromWall
} // namespace socket_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::socket_manager::GetDistanceFromWall > {
  static const char* value()
  {
    return "f5ce5a6c4be1c6cf0d2e7b537eee9c1c";
  }

  static const char* value(const ::socket_manager::GetDistanceFromWall&) { return value(); }
};

template<>
struct DataType< ::socket_manager::GetDistanceFromWall > {
  static const char* value()
  {
    return "socket_manager/GetDistanceFromWall";
  }

  static const char* value(const ::socket_manager::GetDistanceFromWall&) { return value(); }
};


// service_traits::MD5Sum< ::socket_manager::GetDistanceFromWallRequest> should match 
// service_traits::MD5Sum< ::socket_manager::GetDistanceFromWall > 
template<>
struct MD5Sum< ::socket_manager::GetDistanceFromWallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::socket_manager::GetDistanceFromWall >::value();
  }
  static const char* value(const ::socket_manager::GetDistanceFromWallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::socket_manager::GetDistanceFromWallRequest> should match 
// service_traits::DataType< ::socket_manager::GetDistanceFromWall > 
template<>
struct DataType< ::socket_manager::GetDistanceFromWallRequest>
{
  static const char* value()
  {
    return DataType< ::socket_manager::GetDistanceFromWall >::value();
  }
  static const char* value(const ::socket_manager::GetDistanceFromWallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::socket_manager::GetDistanceFromWallResponse> should match 
// service_traits::MD5Sum< ::socket_manager::GetDistanceFromWall > 
template<>
struct MD5Sum< ::socket_manager::GetDistanceFromWallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::socket_manager::GetDistanceFromWall >::value();
  }
  static const char* value(const ::socket_manager::GetDistanceFromWallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::socket_manager::GetDistanceFromWallResponse> should match 
// service_traits::DataType< ::socket_manager::GetDistanceFromWall > 
template<>
struct DataType< ::socket_manager::GetDistanceFromWallResponse>
{
  static const char* value()
  {
    return DataType< ::socket_manager::GetDistanceFromWall >::value();
  }
  static const char* value(const ::socket_manager::GetDistanceFromWallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SOCKET_MANAGER_MESSAGE_GETDISTANCEFROMWALL_H
