(cl:defpackage socket_manager-srv
  (:use )
  (:export
   "GETDISTANCEFROMWALL"
   "<GETDISTANCEFROMWALL-REQUEST>"
   "GETDISTANCEFROMWALL-REQUEST"
   "<GETDISTANCEFROMWALL-RESPONSE>"
   "GETDISTANCEFROMWALL-RESPONSE"
  ))

